// src/config/personalities.ts

export interface Personality {
  name: string;
  icon: string;
}

export const personalities: Personality[] = [
  { name: "skeletor", icon: "skeletor.png" },
  { name: "doctordoom", icon: "doctordoom.png" },
  { name: "elizabeth", icon: "elizabeth.png" },
  { name: "skippy", icon: "skippy.png" },
  { name: "bob", icon: "bob.png" },
  { name: "hermione", icon: "hermione.png" },
  // Add more personalities here
  { name: "doctor1", icon: "doctor1.png" },
  { name: "doctor2", icon: "doctor2.png" },
  { name: "doctor3", icon: "doctor3.png" },
  { name: "doctor4", icon: "doctor4.png" },
  { name: "doctor5", icon: "doctor5.png" },
  { name: "doctor6", icon: "doctor6.png" },
  { name: "doctor7", icon: "doctor7.png" },
  { name: "doctor8", icon: "doctor8.png" },
  { name: "doctor9", icon: "doctor9.png" },
  { name: "doctor10", icon: "doctor10.png" },
  { name: "doctor11", icon: "doctor11.png" },
  { name: "doctor12", icon: "doctor12.png" },
  { name: "doctor13", icon: "doctor13.png" },
  { name: "doctor14", icon: "doctor14.png" },
  { name: "doctor15", icon: "doctor15.png" },
  { name: "docbrown", icon: "docbrown.png" },
  { name: "ricksanchez", icon: "ricksanchez.png" },
  { name: "morty", icon: "morty.png" },
  { name: "q", icon: "q.png" },
  { name: "wolverine", icon: "wolverine.png" },
  { name: "drstrange", icon: "drstrange.png" },
  { name: "wong", icon: "wong.png" },
  { name: "megatron", icon: "megatron.png" },
  { name: "starscream", icon: "starscream.png" },
  { name: "cobracommander", icon: "cobracommander.png" },
  { name: "wrecker", icon: "wrecker.png" },
  { name: "tech", icon: "tech.png" },
  { name: "spaceghost", icon: "spaceghost.png" },
  { name: "zorak", icon: "zorak.png" },
  { name: "brak", icon: "brak.png" },
  { name: "mastershake", icon: "mastershake.png" },
  { name: "frylock", icon: "frylock.png" },
  { name: "meatwad", icon: "meatwad.png" },
  { name: "ignignokt", icon: "ignignokt.png" },
  { name: "err", icon: "err.png" },
  { name: "hal", icon: "hal.png" },
  { name: "kitt", icon: "kitt.png" },
  { name: "murdoch", icon: "murdoch.png" },
  { name: "babarackus", icon: "babarackus.png" },
];
