export interface Personality {
  display_name: string;
  name: string;
  icon: string;
  category: string;
}

export const personalities: Personality[] = [
  {
    display_name: "B. A. Baracus",
    name: "babarackus",
    icon: "babarackus.png",
    category: "A-Team",
  },
  {
    display_name: "Beaker",
    name: "beaker",
    icon: "beaker.png",
    category: "Muppets",
  },
  {
    display_name: "Beckett Mariner",
    name: "mariner",
    icon: "mariner.png",
    category: "Star Trek: Lower Decks",
  },
  {
    display_name: "Bender",
    name: "bender",
    icon: "bender.png",
    category: "Futurama",
  },
  {
    display_name: "Bob The Skull",
    name: "bob",
    icon: "bob.png",
    category: "Dresden Files",
  },
  {
    display_name: "Bob Belcher",
    name: "bobbelcher",
    icon: "bobbelcher.png",
    category: "Bob's Burgers",
  },
  {
    display_name: "Brad Boimler",
    name: "boimler",
    icon: "boimler.png",
    category: "Star Trek: Lower Decks",
  },
  {
    display_name: "Brak",
    name: "brak",
    icon: "brak.png",
    category: "Space Ghost Coast to Coast",
  },
  {
    display_name: "Bunsen Honeydew",
    name: "bunsen",
    icon: "bunsen.png",
    category: "Muppets",
  },
  {
    display_name: "Calcifer",
    name: "calcifer",
    icon: "calcifer.png",
    category: "Howl's Moving Castle",
  },
  {
    display_name: "Capt. Jack Sparrow",
    name: "jacksparrow",
    icon: "jacksparrow.png",
    category: "Pirates of the Caribbean",
  },
  {
    display_name: "Captain Carol Freeman",
    name: "captainfreeman",
    icon: "captainfreeman.png",
    category: "Star Trek",
  },
  {
    display_name: "Chopper",
    name: "chopper",
    icon: "chopper.png",
    category: "Star Wars: Rebels",
  },
  {
    display_name: "Cobra Commander",
    name: "cobracommander",
    icon: "cobracommander.png",
    category: "GI Joe",
  },
  {
    display_name: "D'Vana Tendi",
    name: "tendi",
    icon: "tendi.png",
    category: "Star Trek: Lower Decks",
  },
  {
    display_name: "Darth Vader",
    name: "darthvader",
    icon: "darthvader.png",
    category: "Star Wars",
  },
  {
    display_name: "Doc Brown",
    name: "docbrown",
    icon: "docbrown.png",
    category: "Back to the Future",
  },
  {
    display_name: "Doctor Doom",
    name: "doctordoom",
    icon: "doctordoom.png",
    category: "Marvel",
  },
  {
    display_name: "Doctor Strange",
    name: "drstrange",
    icon: "drstrange.png",
    category: "Marvel",
  },
  {
    display_name: "Dr. T'Ana",
    name: "drtana",
    icon: "drtana.png",
    category: "Star Trek: Lower Decks",
  },
  {
    display_name: "Dr. Zoidberg",
    name: "zoidberg",
    icon: "zoidberg.png",
    category: "Futurama",
  },
  {
    display_name: "Elizabeth Zott",
    name: "zott",
    icon: "zott.png",
    category: "Lessons in Chemistry",
  },
  {
    display_name: "Err",
    name: "err",
    icon: "err.png",
    category: "Aqua Teen Hunger Force",
  },
  {
    display_name: "Ezra Bridger",
    name: "ezra",
    icon: "ezra.png",
    category: "Star Wars: Rebels",
  },
  {
    display_name: "Floyd Pepper",
    name: "floydpepper",
    icon: "floydpepper.png",
    category: "Muppets",
  },
  {
    display_name: "Fozzy Bear",
    name: "fozzy",
    icon: "fozzy.png",
    category: "Muppets",
  },
  { display_name: "Fry", name: "fry", icon: "fry.png", category: "Futurama" },
  {
    display_name: "Frylock",
    name: "frylock",
    icon: "frylock.png",
    category: "Aqua Teen Hunger Force",
  },
  {
    display_name: "Gandalf",
    name: "gandalf",
    icon: "gandalf.png",
    category: "Lord of the Rings",
  },
  {
    display_name: "Garazeb Orrelios",
    name: "zeb",
    icon: "zeb.png",
    category: "Star Wars: Rebels",
  },
  {
    display_name: "Gayle",
    name: "gayle",
    icon: "gayle.png",
    category: "Bob's Burgers",
  },
  {
    display_name: "Gene",
    name: "gene",
    icon: "gene.png",
    category: "Bob's Burgers",
  },
  {
    display_name: "Gonzo",
    name: "gonzo",
    icon: "gonzo.png",
    category: "Muppets",
  },
  {
    display_name: "Grand Admiral Thrawn",
    name: "admiralthrawn",
    icon: "admiralthrawn.png",
    category: "Star Wars: Rebels",
  },
  {
    display_name: "Groot",
    name: "groot",
    icon: "groot.png",
    category: "Marvel",
  },
  {
    display_name: "HAL 9000",
    name: "hal",
    icon: "hal.png",
    category: "2001: A Space Odyssey",
  },
  {
    display_name: "Hera Syndulla",
    name: "hera",
    icon: "hera.png",
    category: "Star Wars: Rebels",
  },
  {
    display_name: "Hermes Conrad",
    name: "hermes",
    icon: "hermes.png",
    category: "Futurama",
  },
  {
    display_name: "Hermione Granger",
    name: "hermione",
    icon: "hermione.png",
    category: "Harry Potter",
  },
  {
    display_name: "Wizard Howl Pendragon",
    name: "howl",
    icon: "howl.png",
    category: "Howl's Moving Castle",
  },
  {
    display_name: "Howling Mad Murdock (From the A-Team)",
    name: "murdock",
    icon: "murdock.png",
    category: "A-Team",
  },
  {
    display_name: "Ignignokt",
    name: "ignignokt",
    icon: "ignignokt.png",
    category: "Aqua Teen Hunger Force",
  },
  {
    display_name: "Iron Man",
    name: "ironman",
    icon: "ironman.png",
    category: "Marvel",
  },
  {
    display_name: "K.I.T.T.",
    name: "kitt",
    icon: "kitt.png",
    category: "Knight Rider",
  },
  {
    display_name: "Kermit the Frog",
    name: "kermit",
    icon: "kermit.png",
    category: "Muppets",
  },
  {
    display_name: "Leela",
    name: "leela",
    icon: "leela.png",
    category: "Futurama",
  },
  {
    display_name: "Linda Belcher",
    name: "linda",
    icon: "linda.png",
    category: "Bob's Burgers",
  },
  {
    display_name: "Link Heartthrob",
    name: "linkheartthrob",
    icon: "linkheartthrob.png",
    category: "Muppets",
  },
  {
    display_name: "Louise Belcher",
    name: "louise",
    icon: "louise.png",
    category: "Bob's Burgers",
  },
  {
    display_name: "Lt. Data",
    name: "data",
    icon: "data.png",
    category: "Star Trek",
  },
  {
    display_name: "Master Shake",
    name: "mastershake",
    icon: "mastershake.png",
    category: "Aqua Teen Hunger Force",
  },
  {
    display_name: "Meatwad",
    name: "meatwad",
    icon: "meatwad.png",
    category: "Aqua Teen Hunger Force",
  },
  {
    display_name: "Megatron",
    name: "megatron",
    icon: "megatron.png",
    category: "Transformers",
  },
  {
    display_name: "Miss Piggy",
    name: "mspiggy",
    icon: "mspiggy.png",
    category: "Muppets",
  },
  { display_name: "Mom", name: "mom", icon: "mom.png", category: "Futurama" },
  {
    display_name: "Morty",
    name: "morty",
    icon: "morty.png",
    category: "Rick and Morty",
  },
  {
    display_name: "Nibbler",
    name: "nibbler",
    icon: "nibbler.png",
    category: "Futurama",
  },
  {
    display_name: "Obi-Wan Kenobi",
    name: "obiwan",
    icon: "obiwan.png",
    category: "Star Wars",
  },
  {
    display_name: "Professor Farnsworth",
    name: "farnsworth",
    icon: "farnsworth.png",
    category: "Futurama",
  },
  {
    display_name: "Q (from Star Trek: TNG)",
    name: "q",
    icon: "q.png",
    category: "Star Trek",
  },
  {
    display_name: "Qui-Gon Jinn",
    name: "quigon",
    icon: "quigon.png",
    category: "Star Wars",
  },
  {
    display_name: "Rick Sanchez",
    name: "ricksanchez",
    icon: "ricksanchez.png",
    category: "Rick and Morty",
  },
  {
    display_name: "Sabine Wren",
    name: "sabine",
    icon: "sabine.png",
    category: "Star Wars: Rebels",
  },
  {
    display_name: "Sam Rutherford",
    name: "rutherford",
    icon: "rutherford.png",
    category: "Star Trek: Lower Decks",
  },
  {
    display_name: "Sherlock Holmes",
    name: "sherlock",
    icon: "sherlock.png",
    category: "Sherlock Holmes",
  },
  {
    display_name: "Skeletor",
    name: "skeletor",
    icon: "skeletor.png",
    category: "Masters of the Universe",
  },
  {
    display_name: "Skippy The Magnificent",
    name: "skippy",
    icon: "skippy.png",
    category: "Expiditionary Force",
  },
  {
    display_name: "Snake Eyes",
    name: "snakeeyes",
    icon: "snakeeyes.png",
    category: "GI Joe",
  },
  {
    display_name: "Sophie",
    name: "sophie",
    icon: "sophie.png",
    category: "Howl's Moving Castle",
  },
  {
    display_name: "Space Ghost",
    name: "spaceghost",
    icon: "spaceghost.png",
    category: "Space Ghost Coast to Coast",
  },
  {
    display_name: "Spock",
    name: "spock",
    icon: "spock.png",
    category: "Star Trek",
  },
  {
    display_name: "Starscream",
    name: "starscream",
    icon: "starscream.png",
    category: "Transformers",
  },
  {
    display_name: "Statler and Waldorf",
    name: "statlerwaldorf",
    icon: "statlerwaldorf.png",
    category: "Muppets",
  },
  {
    display_name: "Swedish Chef",
    name: "swedishchef",
    icon: "swedishchef.png",
    category: "Muppets",
  },
  {
    display_name: "Tech (Bad Batch)",
    name: "tech",
    icon: "tech.png",
    category: "Star Wars: Bad Batch",
  },
  {
    display_name: "The Eighth Doctor",
    name: "doctor8",
    icon: "doctor8.png",
    category: "Doctor Who",
  },
  {
    display_name: "The Eleventh Doctor",
    name: "doctor11",
    icon: "doctor11.png",
    category: "Doctor Who",
  },
  {
    display_name: "The Fifteenth Doctor",
    name: "doctor15",
    icon: "doctor15.png",
    category: "Doctor Who",
  },
  {
    display_name: "The Fifth Doctor",
    name: "doctor5",
    icon: "doctor5.png",
    category: "Doctor Who",
  },
  {
    display_name: "The First Doctor",
    name: "doctor1",
    icon: "doctor1.png",
    category: "Doctor Who",
  },
  {
    display_name: "The Fourth Doctor",
    name: "doctor4",
    icon: "doctor4.png",
    category: "Doctor Who",
  },
  {
    display_name: "The Ninth Doctor",
    name: "doctor9",
    icon: "doctor9.png",
    category: "Doctor Who",
  },
  {
    display_name: "The Second Doctor",
    name: "doctor2",
    icon: "doctor2.png",
    category: "Doctor Who",
  },
  {
    display_name: "The Seventh Doctor",
    name: "doctor7",
    icon: "doctor7.png",
    category: "Doctor Who",
  },
  {
    display_name: "The Sixth Doctor",
    name: "doctor6",
    icon: "doctor6.png",
    category: "Doctor Who",
  },
  {
    display_name: "The Tenth Doctor",
    name: "doctor10",
    icon: "doctor10.png",
    category: "Doctor Who",
  },
  {
    display_name: "The Third Doctor",
    name: "doctor3",
    icon: "doctor3.png",
    category: "Doctor Who",
  },
  {
    display_name: "The Thirteenth Doctor",
    name: "doctor13",
    icon: "doctor13.png",
    category: "Doctor Who",
  },
  {
    display_name: "The Twelfth Doctor",
    name: "doctor12",
    icon: "doctor12.png",
    category: "Doctor Who",
  },
  {
    display_name: "Tomax and Xamot",
    name: "tomaxandxamot",
    icon: "tomaxandxamot.png",
    category: "GI Joe",
  },
  {
    display_name: "Wolverine",
    name: "wolverine",
    icon: "wolverine.png",
    category: "X-Men",
  },
  { display_name: "Wong", name: "wong", icon: "wong.png", category: "Marvel" },
  {
    display_name: "Wrecker (Bad Batch)",
    name: "wrecker",
    icon: "wrecker.png",
    category: "Star Wars: Bad Batch",
  },
  {
    display_name: "Grogu",
    name: "grogu",
    icon: "grogu.png",
    category: "Star Wars",
  },
  {
    display_name: "Yoda",
    name: "yoda",
    icon: "yoda.png",
    category: "Star Wars",
  },
  {
    display_name: "Zapp Brannigan",
    name: "zapp",
    icon: "zapp.png",
    category: "Futurama",
  },
  {
    display_name: "Zorak",
    name: "zorak",
    icon: "zorak.png",
    category: "Space Ghost Coast to Coast",
  },
];
